### PR TITLE
add spark comparison functions

### PR DESCRIPTION
**Pull request by yma11**
add comparison vector functions for equalto, lessthan, greaterthan, lessthanorequal and greaterthanorequal. NaN value is specially handled.

### CODE REVIEW

**Comment by yma11** [comment]
@PHILO-HE Seems no need update functions internal. Add some tests for Infinity, referring spark [doc](https://github.com/apache/spark/blob/master/docs/sql-ref-datatypes.md).

**Comment by PHILO-HE** [comment]
Vector function has a null behavior by default, which produces null result if any input is null. So I think we can skip the check for null. See `VectorFunction.h`:
```
  virtual bool isDefaultNullBehavior() const {
    return true;
  }
```
Thanks!

**Comment by yma11** [comment]
> Vector function has a null behavior by default, which produces null result if any input is null. So I think we can skip the check for null. See `VectorFunction.h`:
> 
> ```
>   virtual bool isDefaultNullBehavior() const {
>     return true;
>   }
> ```
> 
> Thanks!

updated.

**Review by philo-he — APPROVED** [review]
LGTM

**Pull request merged**
