### PR TITLE
set registerCompanion and overwrite for spark max_by/min_by agg functions

### PR DESCRIPTION
**Pull request by Yohahaha**

### CODE REVIEW

**Comment by Yohahaha** [comment]
If your folks could do this change, I would like to close it. :) @rui-mo @PHILO-HE

**Comment by rui-mo** [comment]
Oops... Seems I missed this change. Will add it to the corresponding PR.

**Comment by rui-mo** [comment]
Covered by https://github.com/oap-project/velox/commit/80988e41ab94ebd24f94b9e24c313269d178b7d2.

**Comment by philo-he** [comment]
Hi @Yohahaha, I am closing this PR since another commit already covers it. Please re-open it if you need. Thanks!

**Pull request closed without merging**
