### PR TITLE
implement vread for input stream

### PR DESCRIPTION
**Pull request by zhli1142015**
implement vread for input stream

### CODE REVIEW

**Comment by zhli1142015** [comment]
@zhouyuan , thanks.

**Review by zhouyuan — APPROVED** [review]
👍

**Comment by Yohahaha** [comment]
I see Gluten#1341 does not trigger vread, is any context I missed? 
@zhouyuan @zhli1142015

**Comment by zhli1142015** [comment]
> I see Gluten#1341 does not trigger vread, is any context I missed? @zhouyuan @zhli1142015

Hello @Yohahaha ,
If you want to enable VRead, you need set this flag: https://github.com/oap-project/velox/blob/main/velox/dwio/common/BufferedInput.cpp#L21.
I'm working on our own file system and actually implement parallel data loading by the thread pool in  `preadv` method (I also referenced your PR: https://github.com/facebookincubator/velox/pull/4276, thanks :) ). I only tested with our file system, but not sure how this benefits for others like S3, so it's not enabled by default.
Thanks.

**Comment by Yohahaha** [comment]
Hi @zhli1142015 
Could you share your test results between preadv-on and preadv-off?

**Comment by zhli1142015** [comment]
> Hi @zhli1142015 Could you share your test results between preadv-on and preadv-off?

4% for 1TB TPCDS, thanks.

**Pull request merged**
