### PR TITLE
agg enable corr covar_pop and covar_samp

### PR DESCRIPTION
**Pull request by liujiayi771**
enable corr, covar_pop and covar_samp.

### CODE REVIEW

**Review by rui-mo — APPROVED** [review]

**Comment by zhejiangxiaomai** [comment]
Would you create a pr to upstream this change to velox community when you are free? @liujiayi771

**Comment by liujiayi771** [comment]
> Would you create a pr to upstream this change to velox community when you are free? @liujiayi771

OK. I will discuss this order of calculation with meta. Because the current modification is to meet the calculation results consistent with spark, but it may lead to inconsistent results with presto, we need to see how to solve it better.

**Comment by zhejiangxiaomai** [comment]
> > Would you create a pr to upstream this change to velox community when you are free? @liujiayi771
> 
> OK. I will discuss this order of calculation with meta. Because the current modification is to meet the calculation results consistent with spark, but it may lead to inconsistent results with presto, we need to see how to solve it better.

Thank you very much to explain the root cause.

**Comment by liujiayi771** [comment]
> > > Would you create a pr to upstream this change to velox community when you are free? @liujiayi771
> > 
> > 
> > OK. I will discuss this order of calculation with meta. Because the current modification is to meet the calculation results consistent with spark, but it may lead to inconsistent results with presto, we need to see how to solve it better.
> 
> Thank you very much to explain the root cause.

I will try to fix this on our side without change Velox codes.

**Comment by liujiayi771** [comment]
We should import Epsilon Compare for floating-point value.

**Comment by rui-mo** [comment]
> We should import Epsilon Compare for floating-point value.

Hi @liujiayi771, do you suggest importing it in Gluten CI?

**Comment by liujiayi771** [comment]
Hi, @rui-mo , maybe we can allow a certain error for floating-point numbers when comparing gluten results with vanilla spark. This is what velox does when comparing results with duckdb.

**Comment by rui-mo** [comment]
> Hi, @rui-mo , maybe we can allow a certain error for floating-point numbers when comparing gluten results with vanilla spark. This is what velox does when comparing results with duckdb.

@liujiayi771 That makes sense to me. We can add some precision tolerance when comparing floats.

**Pull request merged**
