### PR TITLE
Fix ORC related failed UT

### PR DESCRIPTION
**Pull request by chenxu14**

### CODE REVIEW

**Comment by zuochunwei** [comment]
@rui-mo could you have a look for this PR

**Comment by rui-mo** [comment]
Thanks. Can we open this change to Velox upstream? We can pick them back to this branch.

**Comment by chenxu14** [comment]
> Thanks. Can we open this change to Velox upstream? We can pick them back to this branch.

There are already some PR's Including this part of logic, such as [6156](https://github.com/facebookincubator/velox/pull/6156) and [6240](https://github.com/facebookincubator/velox/pull/6240), Do you think there is a need to submit a new PR？cc @Yuhta

**Comment by rui-mo** [comment]
@chenxu14 Thanks, I see. Maybe we can keep this PR in our local repo to get ORC work with minimal change.

**Comment by PengleiShi** [comment]
> @chenxu14 Thanks, I see. Maybe we can keep this PR in our local repo to get ORC work with minimal change.

@rui-mo any update here?

**Comment by rui-mo** [comment]
@chenxu14 We are frequently rebasing the base branch. Could you rebase this PR?

**Comment by zhouyuan** [comment]
It looks like the diff is wrong as we force-push to update branch, the workable commit is this one:

https://github.com/oap-project/velox/pull/417/commits/47ed8247753c10d4f191ae336c234d19c3af592d

**Comment by kecookier** [comment]
> It looks like the diff is wrong as we force-push to update branch, the workable commit is this one:
> 
> [47ed824](https://github.com/oap-project/velox/commit/47ed8247753c10d4f191ae336c234d19c3af592d)

@chenxu14

**Comment by chenxu14** [comment]
have rebased my own branch, can you help to review this @zhouyuan

**Comment by chenxu14** [comment]
> @chenxu14 We are frequently rebasing the base branch. Could you rebase this PR?

Done. 
Sorry，don't read emails too much

**Comment by zhouyuan** [comment]
@chenxu14 thanks, can you please also update the gluten one? 
https://github.com/oap-project/gluten/pull/3437

**Comment by chenxu14** [comment]
> @chenxu14 thanks, can you please also update the gluten one? [oap-project/gluten#3437](https://github.com/oap-project/gluten/pull/3437)

OK, will do it after #417 merge, than we can change #3437 to target on the main branch

**Pull request merged**
