### PR TITLE
Add RequestID in VELOX_CHECK_AWS_OUTCOME

### PR DESCRIPTION
**Pull request by leesf**
velox PR: https://github.com/facebookincubator/velox/pull/5478

### CODE REVIEW

**Comment by leesf** [comment]
@zhejiangxiaomai would you please help review this PR? Thanks

**Comment by zhejiangxiaomai** [comment]
> @zhejiangxiaomai would you please help review this PR? Thanks

Thanks, would you rebase this pr?@leesf

**Comment by leesf** [comment]
> > @zhejiangxiaomai would you please help review this PR? Thanks
> 
> Thanks, would you rebase this pr?@leesf

Done

**Comment by zhejiangxiaomai** [comment]
It's best to wait until the velox community merge it and I will pick it.

**Pull request closed without merging**
