### PR TITLE
[Gluten-4433][VL] timestamp conversion for int and string

### LINKED ISSUE #4433: Wrong result for cast(timestamp as string) and cast(int as timestamp)
### Backend

VL (Velox)

### Bug description

To reproduce: https://github.com/oap-project/gluten/pull/4414/files#diff-d6f3816bd1517d3d8708ba5673298038b807726d79abf2b8f8f0584aac636752R779.

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by sharmaplkt**
Support for cast conversion from int or string to timestamp was missing. 

Added functionality to convert int/string to timestamp.
Fixes: https://github.com/oap-project/gluten/issues/4433

### CODE REVIEW

**Comment by Surbhi-Vijay** [comment]
can this PR be created in Meta/velox?

**Comment by rui-mo** [comment]
@sharmaplkt @pulkitsharma7 Thanks for your work. It would be preferred to create two separate PRs for this change in Meta/Velox for casting int as timestamp, and casting string as timestamp. It would be great to add some unit tests, and you could refer to [CastSuiteBase](https://github.com/apache/spark/blob/master/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/CastSuiteBase.scala#L127-L213) to cover enough cases for casting string as timestamp.

**Comment by rui-mo** [comment]
Hi @sharmaplkt, may I ask if there are any updates for the two mentioned conversions? Thanks.

**Comment by zhouyuan** [comment]
hi @sharmaplkt it looks like this patch has been wiped out with 0 commits. We recently run into this issue and would like to push this change to be merged. Do you mind we take over this and open another patch in Meta/Velox?  CC @rui-mo 

Thanks,
-yuan

**Comment by sharmaplkt** [comment]
@rui-mo @zhouyuan I was away for few weeks. I'll be updating the PR soon. Thanks.

**Comment by rui-mo** [comment]
@sharmaplkt Thank you!

**Pull request closed without merging**
