### PR TITLE
refactor spark window function folder

### PR DESCRIPTION
**Pull request by zhli1142015**
Hello @zhejiangxiaomai ,
I'm adding support for nth_value, looks now spark window functions landing in two different folders. I moved them to one in this PR, please let me know if you want to keep two folders in case.
Thanks.
https://github.com/oap-project/gluten/pull/2176

### CODE REVIEW

**Comment by zhouyuan** [comment]
CC: @JkSelf is helping on refactoring the `Window `

**Comment by PHILO-HE** [comment]
Please do a rebase to fix the format check issue.

**Review by JkSelf — COMMENTED** [review]
LGTM.

**Comment by rui-mo** [comment]
@zhli1142015 Sorry, this PR is reverted to make sure Gluten CI is not broken. We need to merge this PR and the corresponding Gluten PR at the same time. Please ping us when you have time to change the Velox branch. Thanks.

**Comment by zhli1142015** [comment]
Hello @rui-mo ,
I updated the velox branch in Gluten PR. I think they can be merged now~
Thanks.

**Pull request merged**
