### PR TITLE
Fix the array out of bounds while getting offsets

### PR DESCRIPTION
**Pull request by jackylee-ch**
We meet this problem while running with gluten, and we found that the array was out of bounds while getting the last offset. The length of the offsets is `length+1`, thus the last index should be `length` instead of `length+1`. As for the unit tests, they are running normally because it use offset to read data and won't check whether has too many data in stringViewBuffers.

### CODE REVIEW

**Comment by jackylee-ch** [comment]
cc @zhztheplayer @zhouyuan

**Comment by zhztheplayer** [comment]
Thanks @jackylee-ch for raising the issue.

As you mentioned

> The length of the offsets is length+1, thus the last index should be length instead of length+1

IIUC `offsets[length + 1]` was treated as "the last index" to pass to `WrapInBufferViewFunc`, is that correct?

However when I looked into the definition of `WrapInBufferViewFunc`

```
using WrapInBufferViewFunc =
    std::function<BufferPtr(const void* buffer, size_t length)>;
```

The second parameter is supposed to be "length" rather than "last index". Am I missing something here?

**Review by zhztheplayer — APPROVED** [review]

**Comment by zhouyuan** [comment]
@jackylee-ch can you please do a rebase? 

-yuan

**Comment by jackylee-ch** [comment]
> @jackylee-ch can you please do a rebase?

@zhouyuan done

**Pull request merged**
