### PR TITLE
[OPPRO-170] Filter validation for Parquet reader at runtime

### PR DESCRIPTION
**Pull request by zhztheplayer**

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@rui-mo @JkSelf Would you please take a look on this, Thanks.

**Comment by JkSelf** [comment]
LGTM. Thanks @zhztheplayer

**Comment by rui-mo** [comment]
LGTM. But looks like if there is one range not supported for parquet, all filter conditions will not be pushed down. Not sure how will this behaviour affect the performance for parquet. Maybe a solution would be to consider format in filter seperation, and only put those unsupported conditions into remaining filter.

**Comment by zhztheplayer** [comment]
@rui-mo I agree and this should be a phase-one solution to avoid failures. @JkSelf If you can help on future performance optimizations? Let's have the TPC-H able to pass at this time. Thanks a lot.

**Comment by JkSelf** [comment]
@zhztheplayer Sure. I can take the performance optimizations in the future.

**Pull request merged**
