### PR TITLE
Add support to read plain encoded INT96 timestamp from Parquet file

### PR DESCRIPTION
**Pull request by mskapilks**
Current only INT96 dictionary encoded timestamp is supported this PR add support for plain encoding

### CODE REVIEW

**Comment by mskapilks** [comment]
cc: @zhouyuan

**Comment by zhouyuan** [comment]
@mskapilks Thank you for helping on this feature! Could you please help to make a pull request to Meta/Velox? We are now doing daily rebase, so if the pull request is merged by Meta/Velox then it will become available in Gluten very soon.  

CC: @rui-mo is also working on timestamp related enabling. 

thanks, -yuan

**Comment by mskapilks** [comment]
@zhouyuan This PR builds upon the already work done in oap-project/velox to read dictionary encoded timestamp. PR add additional support to read plain encoded as well. In Meta velox timestamp reading from parquet is not supported yet, so could exactly make a PR on Meta/Velox.

**Comment by zhli1142015** [comment]
Hello @zhouyuan  and @rui-mo ,
Looks timestamp parquet reader is only available in  this repo, could you guide @mskapilks , how to process this change? Will you help review this change and merge to Rui's time-stamp change? Or should we wait you check in time stamp support to meta velox, and any timeline for it?
Thanks. 
https://github.com/facebookincubator/velox/commit/d18bae8165b6f327541a5bc9303198dbf4bf569e#diff-58ef2bd79ff4173b5a384a3016d6f7bd7d4b237876251cc9d9910e162993eaaa

**Comment by rui-mo** [comment]
@mskapilks Thank you for the great work. Seems this PR reuses some existing change on timestamp reader. Let me explain the context here.
We opened a PR in Velox, but as Velox community suggested, we'd better start from INT64 support first, and refer to the actual logical type to decode the Parquet. For details, please check https://github.com/facebookincubator/velox/pull/4680#issuecomment-1761076062 and https://github.com/facebookincubator/velox/pull/4680#issuecomment-1767682479.

> Will you help review this change and merge to Rui's time-stamp change? Or should we wait you check in time stamp support to meta velox, and any timeline for it?

As we are lack of bandwidth right now, it will take longer time till we make time to continue this work. If @mskapilks is interested to promote this work in Velox, please feel free to open new PRs. If it is preferred to merge this PR in this repo, it also works for us.

cc @zhli1142015

**Review by rui-mo — COMMENTED** [review]
Better to add a unit test in ParquetTableScanTest to guard the functionality. And please fix the code format. Thanks.

**Comment by mskapilks** [comment]
We are also looking to add INT64 support once this PR get merged. For those I think we can get traction in Meta/Velox.

**Comment by mskapilks** [comment]
Added test. 
I don't think the formatting error is related to my change. It gives error for file DecimalRound.cpp

**Comment by zhouyuan** [comment]
> Added test. I don't think the formatting error is related to my change. It gives error for file DecimalRound.cpp

Indeed, the format issue is introduced in recent rebase. @zhztheplayer will fix it in the next rebase. 

thanks, -yuan

**Comment by mskapilks** [comment]
Any idea why this is failing in build?

image

**Comment by zhouyuan** [comment]
@mskapilks it's not related - the URL for hadoop binary changed. will be fixed in the next rebase. 

https://github.com/oap-project/velox/pull/459#issuecomment-1855166249

**Comment by mskapilks** [comment]
Rebased again. @zhouyuan  @rui-mo  Can you please take a look? Thanks

**Comment by zhouyuan** [comment]
@mskapilks thanks, looks good, I'll pick this in the next rebase

**Comment by mskapilks** [comment]
The failure test DecimalUtilTest.divideWithRoundUp seems unrelated. Will rebase again

**Comment by rui-mo** [comment]
@mskapilks Thanks for your continuous efforts on maintaining this PR.I also met CI failure due to `DecimalUtilTest.divideWithRoundUp`, and it can be fixed with below change.
https://github.com/oap-project/velox/pull/465/files#diff-93fb5c8d85f82393426a2af433500e34465a9937220171dc93d0a002ee8120d9R33
Maybe you could include this change in your PR to get the CI passes, and I am going make a fix for it in Velox upstream.

**Comment by mskapilks** [comment]
@rui-mo  Thanks for suggestion, updated the PR with fix

**Comment by zhouyuan** [comment]
@mskapilks already included this commit in the `update` branch, thanks!

**Pull request closed without merging**
