### PR TITLE
Fix null config in HiveConnector (8038)

### PR DESCRIPTION
**Pull request by Yohahaha**
Quick fix for null config in HiveConnector, could be dropped when https://github.com/facebookincubator/velox/pull/8038 merged.

### CODE REVIEW

**Comment by philo-he** [comment]
CI is red. Please rebase the code. Let's see the CI feedback then.

**Comment by Yohahaha** [comment]
Hi @PHILO-HE , it would be great if your folks could apply this minor patch in your way. 
I dont really want submit patch in oap-velox that may be involved in daily rebase. :)

**Comment by philo-he** [comment]
Hi @zhztheplayer, could you pick this patch when you are doing daily rebase? See issue: https://github.com/oap-project/velox/issues/460.

**Comment by Yohahaha** [comment]
> @Yohahaha seems this is merged in meta/velox. [facebookincubator#8038](https://github.com/facebookincubator/velox/pull/8038)

yeah, thank you for checking!

**Pull request closed without merging**
